// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wimfjmzyubcpozsdhiby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbWZqbXp5dWJjcG96c2RoaWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2Mzg3MjYsImV4cCI6MjA1NTIxNDcyNn0.YniouSIEsm_w7r7jYeJ-mwkF2y7vkRpCLliBqa-ICM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);